### ISSUE TITLE
Installed 1.0.2 into TextMate 2.0.23 on macOS Ventura 13.2.1--never opens

### ISSUE THREAD

**Issue by joelouthan** [wakatime/textmate-wakatime#5]
Hello!

I went to install the plugin within TextMate (either buy double clicking the tmplugin file or installing into the `~/Library/Application Support/TextMate/Plugins` folder).

When I go to open TextMate, nothing happens. I can still use the Menu and even opening a file or project, nothing.

I did think that there is a window I cannot see. But Menu->Window shows no open windows. And I have checked my spaces for a prompt.

Thank you.

**Comment by fathonix** [comment]
Unfortunately this plugin code hasn't been updated since 2015, considering WakaTime has completely rewritten its plugin backend during the time. Because of that, I tried modifying some parts and I finally managed to bring it back to life. You can check out mine on [fathonix/textmate-wakatime](https://github.com/fathonix/textmate-wakatime). (I'm still a bit nervous to make a PR though...)

**Comment by joelouthan** [comment]
@fathonix Oh I will try this out asap. thank you so much. I am going to close this issue.
